import turtle
from turtle import Turtle

def dotted_lines():
    dotted_line = turtle.Turtle()
    dotted_line.color('white')
    dotted_line.shape('square')
    dotted_line.shapesize(1, 0.3)
    dotted_line.penup()
    dotted_line.goto(0, -30)

    dotted_line2 = turtle.Turtle()
    dotted_line2.color('white')
    dotted_line2.shape('square')
    dotted_line2.shapesize(1, 0.3)
    dotted_line2.penup()
    dotted_line2.goto(0, -60)

    dotted_line3 = turtle.Turtle()
    dotted_line3.color('white')
    dotted_line3.shape('square')
    dotted_line3.shapesize(1, 0.3)
    dotted_line3.penup()
    dotted_line3.goto(0, -90)

    dotted_line4 = turtle.Turtle()
    dotted_line4.color('white')
    dotted_line4.shape('square')
    dotted_line4.shapesize(1, 0.3)
    dotted_line4.penup()
    dotted_line4.goto(0, -120)

    dotted_line5 = turtle.Turtle()
    dotted_line5.color('white')
    dotted_line5.shape('square')
    dotted_line5.shapesize(1, 0.3)
    dotted_line5.penup()
    dotted_line5.goto(0, -150)

    dotted_line6 = turtle.Turtle()
    dotted_line6.color('white')
    dotted_line6.shape('square')
    dotted_line6.shapesize(1, 0.3)
    dotted_line6.penup()
    dotted_line6.goto(0, -180)

    dotted_line7 = turtle.Turtle()
    dotted_line7.color('white')
    dotted_line7.shape('square')
    dotted_line7.shapesize(1, 0.3)
    dotted_line7.penup()
    dotted_line7.goto(0, -210)

    dotted_line8 = turtle.Turtle()
    dotted_line8.color('white')
    dotted_line8.shape('square')
    dotted_line8.shapesize(1, 0.3)
    dotted_line8.penup()
    dotted_line8.goto(0, -240)

    dotted_line9 = turtle.Turtle()
    dotted_line9.color('white')
    dotted_line9.shape('square')
    dotted_line9.shapesize(1, 0.3)
    dotted_line9.penup()
    dotted_line9.goto(0, 0)

    dotted_line10 = turtle.Turtle()
    dotted_line10.color('white')
    dotted_line10.shape('square')
    dotted_line10.shapesize(1, 0.3)
    dotted_line10.penup()
    dotted_line10.goto(0, 30)

    dotted_line11 = turtle.Turtle()
    dotted_line11.color('white')
    dotted_line11.shape('square')
    dotted_line11.shapesize(1, 0.3)
    dotted_line11.penup()
    dotted_line11.goto(0, 60)

    dotted_line12 = turtle.Turtle()
    dotted_line12.color('white')
    dotted_line12.shape('square')
    dotted_line12.shapesize(1, 0.3)
    dotted_line12.penup()
    dotted_line12.goto(0, 90)

    dotted_line13 = turtle.Turtle()
    dotted_line13.color('white')
    dotted_line13.shape('square')
    dotted_line13.shapesize(1, 0.3)
    dotted_line13.penup()
    dotted_line13.goto(0, 120)

    dotted_line14 = turtle.Turtle()
    dotted_line14.color('white')
    dotted_line14.shape('square')
    dotted_line14.shapesize(1, 0.3)
    dotted_line14.penup()
    dotted_line14.goto(0, 150)

    dotted_line15 = turtle.Turtle()
    dotted_line15.color('white')
    dotted_line15.shape('square')
    dotted_line15.shapesize(1, 0.3)
    dotted_line15.penup()
    dotted_line15.goto(0, 180)

    dotted_line16 = turtle.Turtle()
    dotted_line16.color('white')
    dotted_line16.shape('square')
    dotted_line16.shapesize(1, 0.3)
    dotted_line16.penup()
    dotted_line16.goto(0, 210)

    dotted_line17 = turtle.Turtle()
    dotted_line17.color('white')
    dotted_line17.shape('square')
    dotted_line17.shapesize(1, 0.3)
    dotted_line17.penup()
    dotted_line17.goto(0, 240)

